/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GitService {
  /**
   * Create a new GitService instance
   *
   * Initializes logging if LIMINAL_LOG environment variable is set.
   * Loads feature flags from LIMINAL_FEATURE_FLAGS environment variable.
   * Uses try_init() to safely handle multiple instantiations.
   */
  constructor()
  isRepository(path: string): Promise<boolean>
  getStatus(repoPath: string): Promise<GitStatus>
  commitFile(repoPath: string, filePath: string, message: string, userName: string, userEmail: string): Promise<string>
  commitFiles(repoPath: string, filePaths: Array<string>, message: string, userName: string, userEmail: string): Promise<string>
  stageFile(repoPath: string, filePath: string): Promise<boolean>
  /**
   * Unstage a file from the index (reset to HEAD state)
   *
   * This operation is safe and preserves the working tree. Changes simply
   * become "unstaged" instead of "staged".
   *
   * # Arguments
   * * `repo_path` - Path to repository
   * * `file_path` - Path to file to unstage
   * * `force` - Reserved for future use (currently ignored, unstaging is inherently safe)
   */
  unstageFile(repoPath: string, filePath: string, force?: boolean | undefined | null): Promise<boolean>
  getStagedFiles(repoPath: string): Promise<Array<string>>
  stageDeletion(repoPath: string, filePath: string): Promise<boolean>
  stageRename(repoPath: string, oldPath: string, newPath: string): Promise<boolean>
  commitStagedChanges(repoPath: string, message: string, userName: string, userEmail: string): Promise<string>
  moveFile(repoPath: string, sourcePath: string, destPath: string, message: string, userName: string, userEmail: string): Promise<string>
  moveDirectory(repoPath: string, sourcePath: string, destPath: string, message: string, userName: string, userEmail: string): Promise<string>
  initRepository(path: string): Promise<boolean>
  initRepositoryWithConfig(path: string, config: RepositoryConfig): Promise<boolean>
  /**
   * Initialize a Git repository in a directory that already contains files.
   * For duplicating an existing project: copy the content into place first,
   * then initialise git over it.
   */
  initRepositoryInExistingDir(path: string): Promise<boolean>
  /**
   * Remove all remotes from a repository.
   * Used when duplicating a repository with its history, so the copy cannot
   * accidentally push to the original's remotes.
   */
  removeAllRemotes(repoPath: string): Promise<Array<string>>
  isRepositoryHealthy(repoPath: string): Promise<RepositoryHealth>
  repairRepository(repoPath: string): Promise<boolean>
  configureRepository(repoPath: string, config: GitConfig): Promise<boolean>
  /** Get a Git configuration value (repo-local only, no global fallback) */
  getConfig(repoPath: string, key: string): Promise<string | null>
  /** Get a Git configuration value with global fallback */
  getConfigWithFallback(repoPath: string, key: string): Promise<string | null>
  /** Set a Git configuration value (repo-local only) */
  setConfig(repoPath: string, key: string, value: string): Promise<void>
  /** Remove a Git configuration value (repo-local only) */
  unsetConfig(repoPath: string, key: string): Promise<void>
  createGitignore(repoPath: string, patterns: Array<string>): Promise<boolean>
  createGitattributes(repoPath: string, rules: Array<string>): Promise<boolean>
  getRepositoryInfo(repoPath: string): Promise<RepositoryInfo>
  getCommitHistory(repoPath: string, limit?: number | undefined | null, offset?: number | undefined | null): Promise<CommitHistory>
  /**
   * Get commit history for a specific file efficiently
   *
   * Uses tree entry OID comparison instead of full diffs for O(1) per-commit filtering.
   * Much faster than scanning all commits and checking diffs.
   */
  getFileHistory(repoPath: string, filePath: string, limit?: number | undefined | null): Promise<CommitHistory>
  getFileAtCommit(repoPath: string, filePath: string, commitHash: string): Promise<FileAtCommit>
  restoreFileFromCommit(repoPath: string, filePath: string, commitHash: string): Promise<boolean>
  /**
   * Discard uncommitted changes in a file (restore to HEAD state)
   *
   * This operation restores the working tree file to match the HEAD commit,
   * discarding any uncommitted changes. Both the working tree and index are
   * updated to match HEAD.
   */
  discardChanges(repoPath: string, filePath: string): Promise<boolean>
  /**
   * Amend the last commit with new changes
   *
   * This operation amends the most recent commit with whatever is currently
   * staged in the index, optionally updating the commit message.
   *
   * # Arguments
   * * `repo_path` - Path to the git repository
   * * `message` - New commit message (if empty, reuse previous message)
   * * `user_name` - Optional user name (empty string = read from config)
   * * `user_email` - Optional user email (empty string = read from config)
   */
  commitAmend(repoPath: string, message: string, userName: string, userEmail: string): Promise<string>
  getDeletedFiles(repoPath: string, limit?: number | undefined | null): Promise<Array<DeletedFileEntry>>
  getFileDiff(repoPath: string, filePath: string): Promise<FileDiff>
  getCommitDiff(repoPath: string, commitHash: string): Promise<CommitDiff>
  /**
   * Get unified diff string for a file (working tree vs HEAD)
   *
   * Returns a unified diff string suitable for display in a diff viewer.
   * Handles new files, binary files, and modified files.
   */
  getDiff(repoPath: string, filePath: string): Promise<string>
  /** List all branches in the repository */
  listBranches(repoPath: string, includeRemote?: boolean | undefined | null): Promise<Array<BranchInfo>>
  /** Get information about the current branch */
  getCurrentBranch(repoPath: string): Promise<BranchInfo | null>
  /** Create a new branch */
  createBranch(repoPath: string, options: CreateBranchOptions): Promise<BranchInfo>
  /** Switch to a different branch */
  checkoutBranch(repoPath: string, branchName: string): Promise<BranchInfo>
  /** Delete a branch (with safety checks) */
  deleteBranch(repoPath: string, branchName: string, force?: boolean | undefined | null): Promise<boolean>
  /** List all tags in the repository */
  listTags(repoPath: string): Promise<Array<TagInfo>>
  /** Create a new tag */
  createTag(repoPath: string, options: CreateTagOptions): Promise<TagInfo>
  /** Delete a tag */
  deleteTag(repoPath: string, tagName: string): Promise<boolean>
  /** Get tag information by name */
  getTag(repoPath: string, tagName: string): Promise<TagInfo | null>
}

/** Tracking information relative to upstream branch */
export interface AheadBehind {
  /** Number of commits ahead of upstream */
  ahead: number
  /** Number of commits behind upstream */
  behind: number
}

export interface BranchInfo {
  /** Branch name (e.g., "main", "feature/new-feature") */
  name: string
  /** Whether this is the currently checked out branch */
  isCurrent: boolean
  /** Whether this is a remote branch */
  isRemote: boolean
  /** Hash of the commit this branch points to */
  commitHash: string
  /** Message of the commit this branch points to */
  commitMessage: string
  /** ISO timestamp of when this branch was last updated */
  lastUpdated: string
  /** How many commits ahead/behind the default branch (for local branches) */
  aheadBehind?: AheadBehind
}

export interface CommitDiff {
  commitHash: string
  parentHash?: string
  files: Array<FileDiff>
  totalAdditions: number
  totalDeletions: number
  filesChanged: number
}

export interface CommitHistory {
  commits: Array<CommitInfo>
  totalCount: number
  hasMore: boolean
}

export interface CommitInfo {
  hash: string
  shortHash: string
  message: string
  authorName: string
  authorEmail: string
  timestamp: string
  parentHashes: Array<string>
  fileChanges: number
  insertions: number
  deletions: number
}

/** Options for creating a new branch */
export interface CreateBranchOptions {
  /** Name for the new branch */
  name: string
  /** Commit hash to branch from (if None, branches from current HEAD) */
  fromCommit?: string
  /** Whether to immediately switch to the new branch after creation */
  checkout: boolean
}

/** Options for creating a new tag */
export interface CreateTagOptions {
  /** Name for the new tag */
  name: string
  /** Commit hash to tag (if None, tags current HEAD) */
  targetCommit?: string
  /** Tag message (if provided, creates annotated tag; otherwise lightweight tag) */
  message?: string
  /** Whether to overwrite existing tag with same name */
  force: boolean
  /** User name for annotated tag signature (optional, falls back to git config) */
  userName?: string
  /** User email for annotated tag signature (optional, falls back to git config) */
  userEmail?: string
}

export interface DeletedFileEntry {
  /** Repo-relative file path (e.g., "pages/foo.md") */
  path: string
  /** Unix timestamp (in seconds) when the file was deleted */
  deletedAt: number
  /** Commit hash where the file was last seen (before deletion) */
  lastCommit: string
  /** Commit message of the deletion commit */
  lastCommitMessage: string
}

export interface DiffHunk {
  oldStart: number
  oldLines: number
  newStart: number
  newLines: number
  lines: Array<DiffLine>
}

export interface DiffLine {
  lineType: string
  content: string
  oldLineNumber?: number
  newLineNumber?: number
}

export interface FileAtCommit {
  path: string
  content: string
  exists: boolean
  commitHash: string
}

export interface FileDiff {
  filePath: string
  oldPath?: string
  status: string
  hunks: Array<DiffHunk>
  additions: number
  deletions: number
  isBinary: boolean
}

export interface FileStatus {
  path: string
  status: string
  staged: boolean
}

export interface GitConfig {
  userName?: string
  userEmail?: string
  coreAutocrlf?: string
  coreSafecrlf?: string
}

export interface GitStatus {
  modifiedFiles: Array<FileStatus>
  deletedFiles: Array<FileStatus>
  addedFiles: Array<FileStatus>
  untrackedFiles: Array<FileStatus>
  stagedFiles: Array<FileStatus>
  renamedFiles: Array<RenamedStatus>
  isClean: boolean
  currentBranch?: string
}

export interface RenamedStatus {
  oldPath: string
  newPath: string
  staged: boolean
}

export interface RepositoryConfig {
  description?: string
  defaultBranch?: string
  lineEnding?: string
}

export interface RepositoryHealth {
  isHealthy: boolean
  issues: Array<string>
  warnings: Array<string>
}

export interface RepositoryInfo {
  path: string
  isBare: boolean
  headCommit?: string
  branchCount: number
  commitCount: number
  hasUncommittedChanges: boolean
  remoteUrls: Array<string>
}

/** Information about a git tag */
export interface TagInfo {
  /** Tag name (e.g., "v1.0.0", "release-candidate") */
  name: string
  /** Hash of the commit this tag points to */
  commitHash: string
  /** Message of the commit this tag points to */
  commitMessage: string
  /** Tag message (for annotated tags only) */
  tagMessage?: string
  /** Tagger information (for annotated tags only) */
  tagger?: string
  /** ISO timestamp of when this tag was created */
  created: string
  /** Whether this is an annotated tag (vs lightweight tag) */
  isAnnotated: boolean
}
