/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GitService {
  /**
   * Create a new GitService instance
   *
   * Initializes logging if LIMINAL_LOG environment variable is set.
   * Loads feature flags from LIMINAL_FEATURE_FLAGS environment variable.
   * Uses try_init() to safely handle multiple instantiations.
   */
  constructor()
  isRepository(path: string): Promise<boolean>
  getStatus(repoPath: string): Promise<GitStatus>
  /**
   * Stage one path and write a commit.
   *
   * **The state on disk is what gets staged.** A path present on disk
   * stages its content; a tracked path that is no longer on disk stages as
   * a deletion; a path that is neither on disk nor tracked fails with
   * `FILE_NOT_FOUND`.
   */
  commitFile(repoPath: string, filePath: string, message: string, userName: string, userEmail: string): Promise<string>
  /**
   * Stage the listed paths and write **one** commit.
   *
   * The whole set lands or nothing does. A change spanning several files is
   * one decision, and splitting it across commits means the history stops
   * recording decisions, reverting it stops being a single operation, and
   * between the commits HEAD holds half a change that a reader can observe.
   *
   * Each path follows the same rule as `commitFile`: the state on disk is
   * what gets staged, so a deletion and an edit commit together. Every path
   * is validated and classified before the index is touched, so a failure
   * on any path leaves the index and HEAD exactly as they were.
   *
   * Repeated paths are de-duplicated, including the absolute and
   * repository-relative spellings of the same path.
   *
   * `NOTHING_TO_COMMIT` is evaluated over the resulting tree, making it a
   * whole-set check rather than a per-path one. An empty list is
   * `INVALID_ARGUMENT`, and so is a list longer than 1000 paths.
   */
  commitFiles(repoPath: string, filePaths: Array<string>, message: string, userName: string, userEmail: string): Promise<string>
  stageFile(repoPath: string, filePath: string): Promise<boolean>
  /**
   * Unstage a file from the index (reset to HEAD state)
   *
   * This operation is safe and preserves the working tree. Changes simply
   * become "unstaged" instead of "staged".
   *
   * # Arguments
   * * `repo_path` - Path to repository
   * * `file_path` - Path to file to unstage
   */
  unstageFile(repoPath: string, filePath: string): Promise<boolean>
  getStagedFiles(repoPath: string): Promise<Array<string>>
  stageDeletion(repoPath: string, filePath: string): Promise<boolean>
  stageRename(repoPath: string, oldPath: string, newPath: string): Promise<boolean>
  commitStagedChanges(repoPath: string, message: string, userName: string, userEmail: string): Promise<string>
  moveFile(repoPath: string, sourcePath: string, destPath: string, message: string, userName: string, userEmail: string): Promise<string>
  moveDirectory(repoPath: string, sourcePath: string, destPath: string, message: string, userName: string, userEmail: string): Promise<string>
  initRepository(path: string): Promise<boolean>
  initRepositoryWithConfig(path: string, config: RepositoryConfig): Promise<boolean>
  /**
   * Initialize a Git repository in a directory that already contains files.
   * For duplicating an existing project: copy the content into place first,
   * then initialise git over it.
   */
  initRepositoryInExistingDir(path: string, defaultBranch?: string | undefined | null): Promise<boolean>
  /**
   * Remove all remotes from a repository.
   * Used when duplicating a repository with its history, so the copy cannot
   * accidentally push to the original's remotes.
   */
  removeAllRemotes(repoPath: string): Promise<Array<string>>
  /**
   * Take an explicit lock on a repository, held until `release`.
   *
   * Every mutating operation already takes this lock for its own duration,
   * which makes each operation safe and cannot make a **sequence** safe. A
   * host that writes files, runs an external validator over the working
   * tree, then commits or restores, has a window between the write and the
   * commit in which another process using this library can legally
   * interleave: its edit can land mid-validation, be judged by the wrong
   * validator run, or be undone by the first host's restore. Holding a lock
   * across the whole sequence closes that window.
   *
   * ```js
   * const lock = await git.acquireRepositoryLock(repo);
   * try {
   *   await writeFiles();
   *   if (await validate()) {
   *     await git.commitFiles(repo, paths, message, name, email);
   *   }
   * } finally {
   *   await lock.release();
   * }
   * ```
   *
   * Operations issued while this process holds the lock proceed rather than
   * deadlocking. They skip the advisory lock, which this scope already
   * holds, and still take the in-process mutex, so they continue to exclude
   * each other.
   *
   * A second `acquireRepositoryLock` on the same repository is refused with
   * `REPOSITORY_LOCKED` rather than handed back as a reentrant handle,
   * whether the holder is this process or another one. Nested scopes hide
   * bugs about who owns what.
   *
   * `timeoutMs` defaults to the same ten seconds every other operation
   * waits. As everywhere else, the advisory lock is released by the kernel
   * if the process dies, so a crash cannot wedge a repository; a handle
   * leaked inside a live process is the caller's bug, which is what the
   * `finally` above is for.
   *
   * This excludes other users of **this library**. It does not exclude
   * `git` run from a terminal.
   */
  acquireRepositoryLock(repoPath: string, timeoutMs?: number | undefined | null): Promise<RepositoryLock>
  isRepositoryHealthy(repoPath: string): Promise<RepositoryHealth>
  repairRepository(repoPath: string): Promise<boolean>
  configureRepository(repoPath: string, config: GitConfig): Promise<boolean>
  /** Get a Git configuration value (repo-local only, no global fallback) */
  getConfig(repoPath: string, key: string): Promise<string | null>
  /** Get a Git configuration value with global fallback */
  getConfigWithFallback(repoPath: string, key: string): Promise<string | null>
  /** Set a Git configuration value (repo-local only) */
  setConfig(repoPath: string, key: string, value: string): Promise<void>
  /** Remove a Git configuration value (repo-local only) */
  unsetConfig(repoPath: string, key: string): Promise<void>
  createGitignore(repoPath: string, patterns: Array<string>): Promise<boolean>
  createGitattributes(repoPath: string, rules: Array<string>): Promise<boolean>
  getRepositoryInfo(repoPath: string): Promise<RepositoryInfo>
  getCommitHistory(repoPath: string, limit?: number | undefined | null, offset?: number | undefined | null): Promise<CommitHistory>
  /**
   * Get commit history for a specific file efficiently
   *
   * Uses tree entry OID comparison instead of full diffs for O(1) per-commit filtering.
   * Much faster than scanning all commits and checking diffs.
   */
  getFileHistory(repoPath: string, filePath: string, limit?: number | undefined | null): Promise<CommitHistory>
  /**
   * Resolve a symbolic ref to the commit hash it names, fully peeled.
   *
   * `refName` is `"HEAD"`, a branch name, a tag name, or a full ref path
   * such as `refs/tags/v1.0.0`. An annotated tag peels through to the
   * commit. A raw 40-character commit hash resolves to itself, so a caller
   * can accept either form without branching on which it got.
   *
   * This is the intended way to obtain the hash that `getFileAtCommit` and
   * `getTreeAtCommit` require: resolve once, then pass the result to every
   * read in the snapshot, so all of them name the same object.
   *
   * Anything that does not name a commit is an error naming the ref, never
   * a null. `REF_NOT_FOUND` for no such ref or a ref that peels to a
   * non-commit such as a tag of a blob; `UNBORN_HEAD` for a symbolic ref
   * whose target does not exist yet, which is `"HEAD"` in a repository
   * with no commits or on a freshly orphaned branch. Those are separate
   * because a caller does different things with them: one branch has no
   * commits *yet*, the other names something that was never going to
   * resolve. An abbreviated hash is not resolved.
   *
   * Not a revparse grammar: `HEAD~3` and `main@{yesterday}` are out of
   * scope. One ref in, one hash out.
   *
   * Read-only. Takes no lock.
   */
  resolveRef(repoPath: string, refName: string): Promise<string>
  /**
   * File content at a commit.
   *
   * Takes a raw commit hash and nothing else. `resolveRef` is the intended
   * way to obtain one from `"HEAD"`, a branch or a tag.
   */
  getFileAtCommit(repoPath: string, filePath: string, commitHash: string): Promise<FileAtCommit>
  /**
   * List the paths present at a commit.
   *
   * The paired half of `getFileAtCommit`. Calling both with the same
   * commit hash gives a snapshot-consistent view of a whole repository
   * with no lock held and no writer blocked: resolve a commit once, list
   * its tree, then fetch each file at that same commit.
   *
   * Directories are not entries. They are implied by the paths of the
   * files inside them, and paths come back sorted.
   *
   * Takes a raw commit hash and nothing else, exactly as `getFileAtCommit`
   * does. Not a branch, not a tag, not `"HEAD"`. Resolve those first with
   * `resolveRef`, which is what the snapshot pattern does anyway.
   *
   * `pathPrefix` is a literal string prefix on the repository-relative
   * path rather than a directory match, so `"effort"` also matches a file
   * named `effortless.yaml`; pass the trailing slash to filter to a
   * directory. A prefix matching nothing returns an empty array, not an
   * error.
   */
  getTreeAtCommit(repoPath: string, commitHash: string, pathPrefix?: string | undefined | null): Promise<Array<TreeEntry>>
  /**
   * Restore one path to the version held in `commitHash`.
   *
   * Refuses with `UNSTAGED_CHANGES_WOULD_BE_LOST` when the working copy of
   * **that path** differs from HEAD, or exists while HEAD has never heard
   * of it. The check is per-path, not repository-wide: an unrelated dirty
   * file does not block a restore.
   *
   * `force` overrides that refusal, which is the point of it. A write
   * sequence that dies partway leaves a half-written file, and putting the
   * bytes back is the recovery the default guard would otherwise refuse
   * precisely because the write died. It overrides the guard and nothing
   * else: a path absent from the commit is still `FILE_NOT_FOUND`, and
   * nothing on disk moves. Defaults to `false`.
   *
   * For restoring to HEAD specifically, `discardChanges` is the better
   * tool: it force-checks-out the one path through libgit2, so it also
   * updates the index and preserves symlinks, executable bits and CRLF
   * filters, where this operation writes the blob's bytes.
   */
  restoreFileFromCommit(repoPath: string, filePath: string, commitHash: string, force?: boolean | undefined | null): Promise<boolean>
  /**
   * Discard uncommitted changes in a file (restore to HEAD state)
   *
   * This operation restores the working tree file to match the HEAD commit,
   * discarding any uncommitted changes. Both the working tree and index are
   * updated to match HEAD.
   */
  discardChanges(repoPath: string, filePath: string): Promise<boolean>
  /**
   * Amend the last commit with new changes
   *
   * This operation amends the most recent commit with whatever is currently
   * staged in the index, optionally updating the commit message.
   *
   * # Arguments
   * * `repo_path` - Path to the git repository
   * * `message` - New commit message (if empty, reuse previous message)
   * * `user_name` - Optional user name (empty string = read from config)
   * * `user_email` - Optional user email (empty string = read from config)
   */
  commitAmend(repoPath: string, message: string, userName: string, userEmail: string): Promise<string>
  getDeletedFiles(repoPath: string, limit?: number | undefined | null): Promise<Array<DeletedFileEntry>>
  getFileDiff(repoPath: string, filePath: string): Promise<FileDiff>
  getCommitDiff(repoPath: string, commitHash: string): Promise<CommitDiff>
  /**
   * Get unified diff string for a file (working tree vs HEAD)
   *
   * Returns a unified diff string suitable for display in a diff viewer.
   * Handles new files, binary files, and modified files.
   */
  getDiff(repoPath: string, filePath: string): Promise<string>
  /** List all branches in the repository */
  listBranches(repoPath: string, includeRemote?: boolean | undefined | null): Promise<Array<BranchInfo>>
  /** Get information about the current branch */
  getCurrentBranch(repoPath: string): Promise<BranchInfo | null>
  /** Create a new branch */
  createBranch(repoPath: string, options: CreateBranchOptions): Promise<BranchInfo>
  /** Switch to a different branch */
  checkoutBranch(repoPath: string, branchName: string): Promise<BranchInfo>
  /** Delete a branch (with safety checks) */
  deleteBranch(repoPath: string, branchName: string, force?: boolean | undefined | null): Promise<boolean>
  /**
   * What merging `branch` into HEAD would do — without doing it. Does not
   * touch the working tree, the index, or any ref.
   */
  mergeAnalysis(repoPath: string, branch: string): Promise<MergeAnalysis>
  /**
   * Move the current branch forward to `branch` when that is a strict
   * fast-forward. Refuses with `NOT_FAST_FORWARD` when HEAD is already
   * up to date with `branch`, or when the two have diverged — either case
   * needs a real merge, which this does not perform.
   */
  fastForward(repoPath: string, branch: string): Promise<FastForwardResult>
  /**
   * Merge `branch` into HEAD, entirely in memory.
   *
   * Never leaves an in-progress merge behind: a `"conflicted"` outcome
   * reports the three sides of each contested path and writes nothing at
   * all — no `MERGE_HEAD`, no conflict markers, no conflicted index — so a
   * caller who abandons the resolution is left with the repository it
   * started with. Refuses with `UNSTAGED_CHANGES_WOULD_BE_LOST` when a file
   * the merge would change has unsaved edits on disk.
   */
  merge(repoPath: string, branch: string, userName?: string | undefined | null, userEmail?: string | undefined | null): Promise<MergeOutcome>
  /**
   * Read a blob by oid as text — one side of a contested file.
   *
   * Fails with `BLOB_NOT_UTF8` rather than converting lossily, because
   * silently replacing a byte with U+FFFD corrupts a manuscript in a way
   * nobody notices until much later.
   */
  readBlob(repoPath: string, oid: string): Promise<string>
  /**
   * Commit a merge the user resolved by hand.
   *
   * Takes only the resolved pages: the merge is re-run in memory and the
   * resolutions laid over it, so the caller never reproduces libgit2's
   * merge of the pages that merged cleanly. Refuses with `HEAD_MOVED` when
   * HEAD is no longer `expected_head_hash`, and with `INVALID_ARGUMENT`
   * when the resolved set does not match the conflict set exactly.
   */
  commitMerge(repoPath: string, theirRef: string, expectedHeadHash: string, resolvedFiles: Array<ResolvedFile>, message: string, userName?: string | undefined | null, userEmail?: string | undefined | null): Promise<CommitInfo>
  /** List all tags in the repository */
  listTags(repoPath: string): Promise<Array<TagInfo>>
  /** Create a new tag */
  createTag(repoPath: string, options: CreateTagOptions): Promise<TagInfo>
  /** Delete a tag */
  deleteTag(repoPath: string, tagName: string): Promise<boolean>
  /** Get tag information by name */
  getTag(repoPath: string, tagName: string): Promise<TagInfo | null>
  /** List configured remotes. */
  listRemotes(repoPath: string): Promise<Array<RemoteInfo>>
  /** Add a remote. */
  addRemote(repoPath: string, name: string, url: string): Promise<RemoteInfo>
  /** Remove a remote and its remote-tracking branches. */
  removeRemote(repoPath: string, name: string): Promise<boolean>
  /** Change a remote's fetch URL. */
  setRemoteUrl(repoPath: string, name: string, url: string): Promise<RemoteInfo>
  /**
   * Fetch from a remote, updating remote-tracking branches.
   *
   * Touches neither the working tree nor any local branch, so nothing you
   * have can be lost by it.
   */
  fetch(repoPath: string, remoteName: string, credentials?: RemoteCredentials | undefined | null): Promise<FetchResult>
  /** Push a local branch to a remote. */
  push(repoPath: string, remoteName: string, branch: string, credentials?: RemoteCredentials | undefined | null): Promise<PushResult>
  /**
   * Compare a local branch with its upstream.
   *
   * Reads only what the repository already knows, so the answer is as fresh
   * as the last fetch. Call `fetch` first for current information.
   */
  getUpstreamStatus(repoPath: string, branch: string): Promise<UpstreamStatus>
}

/**
 * A repository lock held across a sequence of operations the caller defines.
 *
 * Returned by `acquireRepositoryLock`. Not constructible from JavaScript:
 * a lock exists only because it was acquired.
 */
export declare class RepositoryLock {
  /**
   * Release the lock. Idempotent, so calling it from a `finally` that also
   * runs on the success path is safe.
   *
   * Releasing waits for any operation already running inside the scope to
   * finish, because such an operation skipped the advisory lock on the
   * strength of this scope holding it.
   */
  release(): Promise<void>
  /** Whether this lock is still held. False once `release` has run. */
  get held(): boolean
}

/** Tracking information relative to upstream branch */
export interface AheadBehind {
  /** Number of commits ahead of upstream */
  ahead: number
  /** Number of commits behind upstream */
  behind: number
}

export interface BranchInfo {
  /** Branch name (e.g., "main", "feature/new-feature") */
  name: string
  /** Whether this is the currently checked out branch */
  isCurrent: boolean
  /** Whether this is a remote branch */
  isRemote: boolean
  /** Hash of the commit this branch points to */
  commitHash: string
  /** Message of the commit this branch points to */
  commitMessage: string
  /** ISO timestamp of when this branch was last updated */
  lastUpdated: string
  /** How many commits ahead/behind the default branch (for local branches) */
  aheadBehind?: AheadBehind
}

export interface CommitDiff {
  commitHash: string
  parentHash?: string
  files: Array<FileDiff>
  totalAdditions: number
  totalDeletions: number
  filesChanged: number
}

export interface CommitHistory {
  commits: Array<CommitInfo>
  totalCount: number
  hasMore: boolean
}

export interface CommitInfo {
  hash: string
  shortHash: string
  message: string
  authorName: string
  authorEmail: string
  timestamp: string
  parentHashes: Array<string>
  fileChanges: number
  insertions: number
  deletions: number
}

/**
 * One path libgit2 could not merge on its own, with the three blobs needed
 * to show the writer what happened. Each side is `None` when that side has
 * no version of the page: no ancestor means the page is new on both sides,
 * and a missing `ours`/`theirs` means that side deleted it.
 */
export interface ConflictedFile {
  /** Repo-relative path of the contested file. */
  path: string
  /** Blob oid of the common ancestor's version, if there is one. */
  ancestorOid?: string
  /** Blob oid of HEAD's version, if our side still has the file. */
  oursOid?: string
  /** Blob oid of the merged branch's version, if their side still has it. */
  theirsOid?: string
}

/** Options for creating a new branch */
export interface CreateBranchOptions {
  /** Name for the new branch */
  name: string
  /** Commit hash to branch from (if None, branches from current HEAD) */
  fromCommit?: string
  /** Whether to immediately switch to the new branch after creation */
  checkout: boolean
}

/** Options for creating a new tag */
export interface CreateTagOptions {
  /** Name for the new tag */
  name: string
  /** Commit hash to tag (if None, tags current HEAD) */
  targetCommit?: string
  /** Tag message (if provided, creates annotated tag; otherwise lightweight tag) */
  message?: string
  /** Whether to overwrite existing tag with same name */
  force: boolean
  /** User name for annotated tag signature (optional, falls back to git config) */
  userName?: string
  /** User email for annotated tag signature (optional, falls back to git config) */
  userEmail?: string
}

export interface DeletedFileEntry {
  /** Repo-relative file path (e.g., "pages/foo.md") */
  path: string
  /** Unix timestamp (in seconds) when the file was deleted */
  deletedAt: number
  /** Commit hash where the file was last seen (before deletion) */
  lastCommit: string
  /** Commit message of the deletion commit */
  lastCommitMessage: string
}

export interface DiffHunk {
  oldStart: number
  oldLines: number
  newStart: number
  newLines: number
  lines: Array<DiffLine>
}

export interface DiffLine {
  lineType: string
  content: string
  oldLineNumber?: number
  newLineNumber?: number
}

/** Result of moving the current branch forward to `branch` via `fastForward`. */
export interface FastForwardResult {
  /** Name of the branch that was moved (the branch HEAD was on). */
  branch: string
  /** Commit the branch pointed to before the fast-forward. */
  previousCommitHash: string
  /** Commit the branch points to now — the same commit `branch` pointed to. */
  commitHash: string
}

export interface FetchResult {
  remote: string
  /** Refs whose remote-tracking branch moved, as "refs/heads/main". */
  updatedRefs: Array<string>
  receivedObjects: number
  receivedBytes: number
}

export interface FileAtCommit {
  path: string
  content: string
  exists: boolean
  commitHash: string
}

export interface FileDiff {
  filePath: string
  oldPath?: string
  status: string
  hunks: Array<DiffHunk>
  additions: number
  deletions: number
  isBinary: boolean
}

export interface FileStatus {
  path: string
  status: string
  staged: boolean
}

export interface GitConfig {
  userName?: string
  userEmail?: string
  coreAutocrlf?: string
  coreSafecrlf?: string
}

export interface GitStatus {
  modifiedFiles: Array<FileStatus>
  deletedFiles: Array<FileStatus>
  addedFiles: Array<FileStatus>
  untrackedFiles: Array<FileStatus>
  stagedFiles: Array<FileStatus>
  renamedFiles: Array<RenamedStatus>
  isClean: boolean
  currentBranch?: string
}

/**
 * What merging `branch` into HEAD would do, without doing it.
 *
 * `ahead`/`behind` are always reported relative to `branch`, regardless of
 * `kind` — even when `kind` is `"up-to-date"` HEAD may be ahead by any
 * number of commits; `"up-to-date"` only means `behind` is zero.
 */
export interface MergeAnalysis {
  /**
   * `"up-to-date"` — HEAD already contains everything `branch` has.
   * `"fast-forward"` — HEAD is an ancestor of `branch`; moving the ref is
   * sufficient, no merge commit is needed.
   * `"normal"` — HEAD and `branch` have diverged; a real merge is required.
   */
  kind: string
  /** Commits HEAD has that `branch` does not. */
  ahead: number
  /** Commits `branch` has that HEAD does not. */
  behind: number
}

/**
 * What `merge` did. Exactly one of the four kinds, and the library never
 * leaves an in-progress merge behind for any of them: a `"conflicted"`
 * outcome is a *report*, not a state — nothing was written, there is no
 * `MERGE_HEAD`, and the caller is free to walk away.
 */
export interface MergeOutcome {
  /**
   * `"merged"` — a real merge commit was created.
   * `"fast-forwarded"` — the branch ref moved; no merge commit exists.
   * `"up-to-date"` — HEAD already contained everything; nothing was written.
   * `"conflicted"` — nothing was written; see `conflicts`.
   */
  kind: string
  /**
   * The commit HEAD points at after the operation. `None` — and only
   * `None` — when `kind` is `"conflicted"`.
   */
  commitHash?: string
  /**
   * The contested paths, sorted by path. Empty unless `kind` is
   * `"conflicted"`.
   */
  conflicts: Array<ConflictedFile>
}

export interface PushResult {
  remote: string
  /** Refspecs that were pushed. */
  pushedRefs: Array<string>
}

/**
 * Credentials for a single remote operation.
 *
 * Deliberately passed per call rather than stored. This library has no
 * business owning secrets: the host application knows where they came from
 * (an OS keychain, an environment variable, a prompt) and how long they may
 * live, and it is far better placed to decide. Everything here is optional —
 * see `remote_ops::credential_callback` for the fallback order when a field
 * is absent.
 */
export interface RemoteCredentials {
  /**
   * Username for HTTPS. For a personal access token on GitHub this can be
   * anything non-empty; the token goes in `password`.
   */
  username?: string
  /** Password or personal access token for HTTPS. */
  password?: string
  /** Path to an SSH private key. The matching `.pub` is used if present. */
  sshPrivateKeyPath?: string
  /** Passphrase for the SSH private key, when it has one. */
  sshPassphrase?: string
}

export interface RemoteInfo {
  name: string
  /** Fetch URL. `None` for a remote configured with no URL, which git allows. */
  url?: string
  /** Push URL when it differs from the fetch URL, as `remote.<name>.pushurl`. */
  pushUrl?: string
}

export interface RenamedStatus {
  oldPath: string
  newPath: string
  staged: boolean
}

export interface RepositoryConfig {
  description?: string
  defaultBranch?: string
  lineEnding?: string
}

export interface RepositoryHealth {
  isHealthy: boolean
  issues: Array<string>
  warnings: Array<string>
}

export interface RepositoryInfo {
  path: string
  isBare: boolean
  headCommit?: string
  branchCount: number
  commitCount: number
  hasUncommittedChanges: boolean
  remoteUrls: Array<string>
}

/** A writer's decision about one contested page, handed back to `commitMerge`. */
export interface ResolvedFile {
  /**
   * Repo-relative path. Must be one of the paths `merge` reported as
   * conflicted.
   */
  path: string
  /**
   * The resolved text of the page. `None` resolves the conflict as a
   * deletion — the page is not in the merge commit's tree.
   */
  content?: string
}

/** Information about a git tag */
export interface TagInfo {
  /** Tag name (e.g., "v1.0.0", "release-candidate") */
  name: string
  /** Hash of the commit this tag points to */
  commitHash: string
  /** Message of the commit this tag points to */
  commitMessage: string
  /** Tag message (for annotated tags only) */
  tagMessage?: string
  /** Tagger information (for annotated tags only) */
  tagger?: string
  /** ISO timestamp of when this tag was created */
  created: string
  /** Whether this is an annotated tag (vs lightweight tag) */
  isAnnotated: boolean
}

/**
 * One path present in a commit's tree, as reported by `getTreeAtCommit`.
 *
 * Directories are not entries. They are implied by the paths of the files
 * inside them, which is what lets the result be zipped directly with
 * `getFileAtCommit` calls against the same commit.
 */
export interface TreeEntry {
  /** Repository-relative path, using forward slashes on every platform. */
  path: string
  /** `"file"`, `"symlink"` or `"submodule"`. */
  kind: string
  /**
   * Size of the underlying blob in bytes. For a `"symlink"` this is the
   * length of the target path, since that is what the blob holds. For a
   * `"submodule"` there is no blob and this is `0`.
   */
  size: number
  /**
   * Full oid of the blob at this path. For a `"submodule"` there is no
   * blob, and this is the commit oid the parent repository has recorded
   * for it.
   */
  blobHash: string
}

/**
 * How the local branch stands against its remote-tracking branch.
 *
 * Distinct from `AheadBehind`, which compares two local branches. This one
 * answers "do I need to push, pull, both, or neither", and is only meaningful
 * after a fetch — git cannot know what a remote holds without asking it.
 */
export interface UpstreamStatus {
  branch: string
  /**
   * The tracking branch, as "origin/main". `None` if the branch has no
   * upstream configured, which is not an error.
   */
  upstream?: string
  /** Local commits the upstream does not have. */
  ahead: number
  /** Upstream commits the local branch does not have. */
  behind: number
  /**
   * True when there is no upstream to compare against, so `ahead` and
   * `behind` are both zero for lack of information rather than for lack of
   * difference. Callers must distinguish these or they will report a branch
   * as up to date when they simply do not know.
   */
  noUpstream: boolean
}
